@startuml
class ListController{
    +FXML TextField listName
    +FXML Button addListButton
    +addListHandler()
}

class LocalList{
    +String listName
    +String listDescription
    +ListView()
}

LocalList <|-- ListController
@enduml