@startuml
class SampleListController{
    +FXML Button addTask
    +FXML Button editTask
    +FXML Button removeTask
    +FXML Button deleteList
    +Object[] getTasks()
    +initialize()
    +addTaskHandler()
    +LocalTask()
    +removeTaskHandler()
    +deleteListHandler()
}

@enduml